import { FractalChapter, FractalMatrixZ } from './schema'

export const FRACTAL_MATRIX: FractalChapter[] = [
  { id:1, book:'Book 1', divineName:'Yod', bookName:'Becoming Rooted', bookTheme:'Identity, Calling, and the Formation of Glory', chapterTitle:'Leadership Begins at the Altar', geometryIcon:'Square', stone:'Sardius', element:'Fire', templeSpace:'Altar', storyStage:'Exposition', dimension:'1 Glory', fractalGate:'Revelation', spiritualFrequency:'Deep Stillness', bookColor:'Red', tribe:'Reuben', prf:'Hosea', apostle:'' },
  { id:2, book:'Book 1', divineName:'Yod', bookName:'Becoming Rooted', bookTheme:'Identity, Calling, and the Formation of Glory', chapterTitle:'The Tripartite Leader: Spirit, Soul, and Body', geometryIcon:'Equilateral Triangle', stone:'Topaz', element:'Fire', templeSpace:'Altar', storyStage:'Rising Action', dimension:'6 Image', fractalGate:'Internalization', spiritualFrequency:'Triune Tone', bookColor:'Red', tribe:'Simeon', prf:'Joel', apostle:'' },
  { id:3, book:'Book 1', divineName:'Yod', bookName:'Becoming Rooted', bookTheme:'Identity, Calling, and the Formation of Glory', chapterTitle:'Why We Had to Leave Eden', geometryIcon:'2D Spiral', stone:'Emerald', element:'Fire', templeSpace:'Altar', storyStage:'Climax', dimension:'2 Presence', fractalGate:'Embodiment', spiritualFrequency:'Exilic Echo', bookColor:'Red', tribe:'Levi', prf:'Amos', apostle:'' },
  { id:4, book:'Book 1', divineName:'Yod', bookName:'Becoming Rooted', bookTheme:'Identity, Calling, and the Formation of Glory', chapterTitle:'Formation in Exile: The Purpose of the Fall', geometryIcon:'Isometric Cube', stone:'Carbuncle', element:'Fire', templeSpace:'Altar', storyStage:'Falling Action', dimension:'4 Word', fractalGate:'Integration', spiritualFrequency:'Structure Hum', bookColor:'Red', tribe:'Judah', prf:'Obadiah', apostle:'' },
  { id:5, book:'Book 1', divineName:'Yod', bookName:'Becoming Rooted', bookTheme:'Identity, Calling, and the Formation of Glory', chapterTitle:'The Seed Hidden in the Dust', geometryIcon:'Monad Unity Point', stone:'Onyx', element:'Fire', templeSpace:'Altar', storyStage:'Resolution', dimension:'7 Name', fractalGate:'Hidden (North)', spiritualFrequency:'Subterranean Hum', bookColor:'Red', tribe:'Dan', prf:'Jonah', apostle:'' },
  { id:6, book:'Book 2', divineName:'Heh', bookName:'Becoming Aligned', bookTheme:'Patterns and the Spiritual Core of Leadership', chapterTitle:'Jesus as the Tree of Life, the Flaming Sword, and the Cosmic Unifier', geometryIcon:'Tetrahedron + Rays', stone:'Sapphire', element:'Air', templeSpace:'Holy Place', storyStage:'Exposition', dimension:'6 Image', fractalGate:'Revelation', spiritualFrequency:'Tree Flame Pulse', bookColor:'Blue', tribe:'Naphtali', prf:'Micah', apostle:'' },
  { id:7, book:'Book 2', divineName:'Heh', bookName:'Becoming Aligned', bookTheme:'Patterns and the Spiritual Core of Leadership', chapterTitle:'The Divine Pattern: YHWH’s Structure and the Wings of Wisdom', geometryIcon:'Hexagonal Mandala', stone:'Diamond', element:'Air', templeSpace:'Holy Place', storyStage:'Rising Action', dimension:'4 Word', fractalGate:'Internalization', spiritualFrequency:'Wings of Wisdom Vibration', bookColor:'Blue', tribe:'Gad', prf:'Nahum', apostle:'' },
  { id:8, book:'Book 2', divineName:'Heh', bookName:'Becoming Aligned', bookTheme:'Patterns and the Spiritual Core of Leadership', chapterTitle:'The Pattern Keeper: Heaven’s Interface and Leadership Design', geometryIcon:'Octahedron', stone:'Ligure', element:'Air', templeSpace:'Holy Place', storyStage:'Climax', dimension:'2 Presence', fractalGate:'Embodiment', spiritualFrequency:'Guardian Harmonic', bookColor:'Blue', tribe:'Asher', prf:'Habakkuk', apostle:'' },
  { id:9, book:'Book 2', divineName:'Heh', bookName:'Becoming Aligned', bookTheme:'Patterns and the Spiritual Core of Leadership', chapterTitle:'The Fractal Pattern of Leadership', geometryIcon:'Fibonacci Spiral', stone:'Agate', element:'Air', templeSpace:'Holy Place', storyStage:'Falling Action', dimension:'5 Spirit', fractalGate:'Integration', spiritualFrequency:'Recursive Tone', bookColor:'Blue', tribe:'Issachar', prf:'Zephaniah', apostle:'' },
  { id:10, book:'Book 2', divineName:'Heh', bookName:'Becoming Aligned', bookTheme:'Patterns and the Spiritual Core of Leadership', chapterTitle:'The Invisible Root System of Authority', geometryIcon:'Fractal Tree', stone:'Amethyst', element:'Air', templeSpace:'Holy Place', storyStage:'Resolution', dimension:'7 Name', fractalGate:'Hidden (South)', spiritualFrequency:'Root Resonance', bookColor:'Blue', tribe:'Zebulun', prf:'Haggai', apostle:'' },
  { id:11, book:'Book 3', divineName:'Vav', bookName:'Becoming Clear', bookTheme:'Vision, Emotional Intelligence, and the Inner Compass', chapterTitle:'Vision of God: The First Call of Every Leader', geometryIcon:'Icosahedron', stone:'Beryl', element:'Water', templeSpace:'Inner Light', storyStage:'Exposition', dimension:'1 Glory', fractalGate:'Revelation', spiritualFrequency:'Visionary Call', bookColor:'Teal', tribe:'Joseph (Ephraim)', prf:'Zechariah', apostle:'' },
  { id:12, book:'Book 3', divineName:'Vav', bookName:'Becoming Clear', bookTheme:'Vision, Emotional Intelligence, and the Inner Compass', chapterTitle:'Vision of Self: Emotional Tools and Soul Awareness', geometryIcon:'Hexagonal Prism', stone:'Onyx (2)', element:'Water', templeSpace:'Inner Light', storyStage:'Rising Action', dimension:'3 Voice', fractalGate:'Internalization', spiritualFrequency:'Soul Frequency', bookColor:'Teal', tribe:'Benjamin', prf:'Malachi', apostle:'' },
  { id:13, book:'Book 3', divineName:'Vav', bookName:'Becoming Clear', bookTheme:'Vision, Emotional Intelligence, and the Inner Compass', chapterTitle:'Vision of Mission: Discovering Your Divine Measure', geometryIcon:'Golden Ratio Spiral', stone:'Jasper', element:'Water', templeSpace:'Inner Light', storyStage:'Climax', dimension:'4 Word', fractalGate:'Embodiment', spiritualFrequency:'Mission Tuning', bookColor:'Teal', tribe:'', prf:'John the Baptist', apostle:'Peter' },
  { id:14, book:'Book 3', divineName:'Vav', bookName:'Becoming Clear', bookTheme:'Vision, Emotional Intelligence, and the Inner Compass', chapterTitle:'The Wounded Visionary: Leading Through Inner Conflict', geometryIcon:'Mobius Strip', stone:'Sapphire', element:'Water', templeSpace:'Inner Light', storyStage:'Falling Action', dimension:'6 Image', fractalGate:'Integration', spiritualFrequency:'Wounded Harmony', bookColor:'Teal', tribe:'', prf:'Elijah', apostle:'James (Zebedee)' },
  { id:15, book:'Book 3', divineName:'Vav', bookName:'Becoming Clear', bookTheme:'Vision, Emotional Intelligence, and the Inner Compass', chapterTitle:'Sacred Sight: From Revelation to Discernment', geometryIcon:'Metatron Cube', stone:'Chalcedony', element:'Water', templeSpace:'Inner Light', storyStage:'Resolution', dimension:'7 Name', fractalGate:'Hidden (East)', spiritualFrequency:'Sight Pulse', bookColor:'Teal', tribe:'', prf:'John the Revelator', apostle:'John' },
  { id:16, book:'Book 4', divineName:'Final Heh', bookName:'Becoming Embodied', bookTheme:'Walking in Wisdom, Spirit, and Glory', chapterTitle:'Emotional Intelligence and Passion', geometryIcon:'3D Pentagon', stone:'Emerald (2)', element:'Earth', templeSpace:'Holy of Holies', storyStage:'Exposition', dimension:'5 Spirit', fractalGate:'Revelation', spiritualFrequency:'Passion Current', bookColor:'Green', tribe:'', prf:'Samuel', apostle:'Andrew' },
  { id:17, book:'Book 4', divineName:'Final Heh', bookName:'Becoming Embodied', bookTheme:'Walking in Wisdom, Spirit, and Glory', chapterTitle:'Intelligent Action: Decision-Making in Alignment with the Spirit', geometryIcon:'Tetrahedron', stone:'Sardonyx', element:'Earth', templeSpace:'Holy of Holies', storyStage:'Rising Action', dimension:'4 Word', fractalGate:'Internalization', spiritualFrequency:'Aligned Decision Pulse', bookColor:'Green', tribe:'', prf:'Nathan', apostle:'Philip' },
  { id:18, book:'Book 4', divineName:'Final Heh', bookName:'Becoming Embodied', bookTheme:'Walking in Wisdom, Spirit, and Glory', chapterTitle:'Embodied Leadership: Why Your Body Matters', geometryIcon:'Isometric Grid', stone:'Carnelian', element:'Earth', templeSpace:'Holy of Holies', storyStage:'Climax', dimension:'6 Image', fractalGate:'Embodiment', spiritualFrequency:'Embodied Presence', bookColor:'Green', tribe:'', prf:'Gad', apostle:'Bartholomew' },
  { id:19, book:'Book 4', divineName:'Final Heh', bookName:'Becoming Embodied', bookTheme:'Walking in Wisdom, Spirit, and Glory', chapterTitle:'Mentors and Mirrors: Leading Like Jesus in a Fractured World', geometryIcon:'Reflection Diagram', stone:'Chrysolite', element:'Earth', templeSpace:'Holy of Holies', storyStage:'Falling Action', dimension:'2 Presence', fractalGate:'Integration', spiritualFrequency:'Mirror Tone', bookColor:'Green', tribe:'', prf:'David', apostle:'Matthew' },
  { id:20, book:'Book 4', divineName:'Final Heh', bookName:'Becoming Embodied', bookTheme:'Walking in Wisdom, Spirit, and Glory', chapterTitle:'The Body of Christ: Flesh Made Flame', geometryIcon:'Flower of Life', stone:'Beryl (2)', element:'Earth', templeSpace:'Holy of Holies', storyStage:'Resolution', dimension:'7 Name', fractalGate:'Hidden (West)', spiritualFrequency:'Radiant Bloom', bookColor:'Green', tribe:'', prf:'Isaiah', apostle:'Thomas' },
  { id:21, book:'Book 5', divineName:'YESHUA', bookName:'The Pattern Manifesto', bookTheme:'Jesus, the Fractal Fulfillment, and the Apostolic Flame', chapterTitle:'Yeshua: The Embodiment of YHWH', geometryIcon:'Star of David', stone:'Topaz (2)', element:'Plasma', templeSpace:'Ark', storyStage:'Exposition', dimension:'7 Name', fractalGate:'Revelation', spiritualFrequency:'Incarnational Wave', bookColor:'Gold/White', tribe:'', prf:'Jeremiah', apostle:'James (Alphaeus)' },
  { id:22, book:'Book 5', divineName:'YESHUA', bookName:'The Pattern Manifesto', bookTheme:'Jesus, the Fractal Fulfillment, and the Apostolic Flame', chapterTitle:'The Spiral and the Sword: Jesus as Pattern and Portal', geometryIcon:'Fibonacci Circle', stone:'Chrysoprase', element:'Plasma', templeSpace:'Ark', storyStage:'Rising Action', dimension:'6 Image', fractalGate:'Internalization', spiritualFrequency:'Sword Spiral Resonance', bookColor:'Gold/White', tribe:'', prf:'Ezekiel', apostle:'Thaddeus' },
  { id:23, book:'Book 5', divineName:'YESHUA', bookName:'The Pattern Manifesto', bookTheme:'Jesus, the Fractal Fulfillment, and the Apostolic Flame', chapterTitle:'The Name and the Nations: Fractal Mission in the Latter Days', geometryIcon:'Torus (3D)', stone:'Jacinth', element:'Plasma', templeSpace:'Ark', storyStage:'Climax', dimension:'4 Word', fractalGate:'Embodiment', spiritualFrequency:'Global Pulse', bookColor:'Gold/White', tribe:'', prf:'Daniel', apostle:'Simon the Zealot' },
  { id:24, book:'Book 5', divineName:'YESHUA', bookName:'The Pattern Manifesto', bookTheme:'Jesus, the Fractal Fulfillment, and the Apostolic Flame', chapterTitle:'Pentecost, Fire, and the Echo of Eden', geometryIcon:'64 Star Tetrahedron', stone:'Amethyst (2)', element:'Plasma', templeSpace:'Ark', storyStage:'Falling Action', dimension:'7 Name', fractalGate:'Integration', spiritualFrequency:'Covenant Flame Ring', bookColor:'Gold/White', tribe:'', prf:'Moses', apostle:'Matthias' },
  { id:25, book:'Book 5', divineName:'YESHUA', bookName:'The Pattern Manifesto', bookTheme:'Jesus, the Fractal Fulfillment, and the Apostolic Flame', chapterTitle:'The Commissioning Pattern: Jesus and the Sending of the Flame', geometryIcon:'Nested Fib Circles', stone:'White Sapphire', element:'Plasma', templeSpace:'Ark', storyStage:'Resolution (Hidden: Center)', dimension:'7 Name', fractalGate:'Shofar Convergence', spiritualFrequency:'Shofar Commission Resonance', bookColor:'Gold/White', tribe:'', prf:'Jesus Christ', apostle:'Jesus Christ' },
  { id:26, book:'Book 5', divineName:'YESHUA', bookName:'The Pattern Manifesto', bookTheme:'Jesus, the Fractal Fulfillment, and the Apostolic Flame', chapterTitle:'The Apostolic Flame: Paul and the Global Replication Pattern', geometryIcon:'Fractal Network', stone:'Amethyst (3)', element:'Plasma', templeSpace:'Ark', storyStage:'Rising Action', dimension:'7 Name', fractalGate:'Network Multiplication', spiritualFrequency:'Global Pulse', bookColor:'Gold/White', tribe:'', prf:'Paul', apostle:'Paul' },
  { id:27, book:'Book 5', divineName:'YESHUA', bookName:'The Pattern Manifesto', bookTheme:'Jesus, the Fractal Fulfillment, and the Apostolic Flame', chapterTitle:'The Pattern Sealed', geometryIcon:'New Jerusalem Grid (12-Gate Cube)', stone:'Jasper (4)', element:'Plasma', templeSpace:'Ark', storyStage:'Epilogue (Coda / Seal)', dimension:'7 Name (Seal)', fractalGate:'Twelve-Gate Convergence', spiritualFrequency:'Amen Convergence', bookColor:'Gold/White', tribe:'', prf:'Jesus Christ (Convergence)', apostle:'' }
]

// Validate at module load
FractalMatrixZ.parse(FRACTAL_MATRIX)
